project:
  type: website
  output-dir: docs

website:
  title: "Will Plot That Later"
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - test page.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: article



